<a href="https://colab.research.google.com/github/bongmiin/Language/blob/main/dataMining_Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 배열과 행렬   
array(), matrix( ) 함수를 이용해 생성한다

In [ ]:
z <- array(1:20, dim=c(4, 5))
z

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [ ]:
z <- matrix(1:20, 4, 5)
z

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [ ]:
z <- matrix(2, 4, 5)
z

[,1] [,2] [,3] [,4] [,5]
[1,] 2    2    2    2    2   
[2,] 2    2    2    2    2   
[3,] 2    2    2    2    2   
[4,] 2    2    2    2    2

In [ ]:
z <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2, ncol = 3, byrow = T)
z

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
z[2, 3]

[1] 6

기존의 벡터(들) 또는 행렬을 결합해 새로운 행렬을 만들 수 있다

In [ ]:
x <- 1:4
y <- 5:8
cbind(x, y)

x y
[1,] 1 5
[2,] 2 6
[3,] 3 7
[4,] 4 8

In [ ]:
rbind(x, y)

[,1] [,2] [,3] [,4]
x 1    2    3    4   
y 5    6    7    8

In [ ]:
B <- matrix(0, 4, 5)
cbind(B, 1:4)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0    0    0    0    0    1   
[2,] 0    0    0    0    0    2   
[3,] 0    0    0    0    0    3   
[4,] 0    0    0    0    0    4

In [ ]:
A <- matrix(1:20, 4, 5)
B <- matrix(1:20, 4, 5)
C <- cbind(A, B)
C

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    5     9   13   17   1    5     9   13   17   
[2,] 2    6    10   14   18   2    6    10   14   18   
[3,] 3    7    11   15   19   3    7    11   15   19   
[4,] 4    8    12   16   20   4    8    12   16   20

- cbind( ): 열 방향으로 결합
- rbind( ): 행 방향으로 결합   
    
행렬 간 산술연산은 벡터와 마찬가지로 성분별 연산이다.

In [ ]:
print(A + B)

     [,1] [,2] [,3] [,4] [,5]
[1,]    2   10   18   26   34
[2,]    4   12   20   28   36
[3,]    6   14   22   30   38
[4,]    8   16   24   32   40


In [ ]:
print(A - B)

     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0
[2,]    0    0    0    0    0
[3,]    0    0    0    0    0
[4,]    0    0    0    0    0


두 행렬의 차원이 같지 않은 경우 재사용 규칙X, 에러메세지 발생

## 데이터 프레임
---------------
새로운 데이터 프레임을 생성하려면 data.frame()함수를 이용한다.

--------------
다음은 데이터프레임에 자주 사용되는 기본 함수의 예이다.   
**특히 class( )함수는 객체지향 프로그래밍 측면에서 객체의 클래스 정보를 알려주거나 지정할 수 있는 유용한 함수이니 기억해두자**


In [ ]:
dat.2 <- data.frame(x=1:3, y=c('a','b','c'), stringsAsFactors = F)

In [ ]:
typeof(dat.2)

[1] "list"

In [ ]:
class(dat.2)

[1] "data.frame"

In [ ]:
is.data.frame(dat.2)

[1] TRUE

-----
### R 작업 디렉토리 지정 & csv읽기   
선형회귀분석

In [ ]:
getwd()

[1] "/content/sample_data"

In [ ]:
prod <-read.csv('productivityORG.csv')

In [ ]:
prod$date <- as.Date(prod$date, format= '%m/%d/%y')

In [ ]:
prod$quarter <- factor(prod$quarter)

In [ ]:
prod$department <- factor(prod$department)

In [ ]:
prod$day <- factor(prod$day)
prod$team <- factor(prod$team)

In [ ]:
summary(prod)

      date                quarter        department         day     
 Min.   :2020-01-01   Quarter1:360   finishing:506   Monday   :199  
 1st Qu.:2020-01-18   Quarter2:335   sweing   :691   Saturday :187  
 Median :2020-02-03   Quarter3:210                   Sunday   :203  
 Mean   :2020-02-04   Quarter4:248                   Thursday :199  
 3rd Qu.:2020-02-23   Quarter5: 44                   Tuesday  :201  
 Max.   :2020-03-11                                  Wednesday:208  
                                                                    
      team         target            smv             wip         
 2      :109   Min.   :0.0700   Min.   : 2.90   Min.   :    0.0  
 8      :109   1st Qu.:0.7000   1st Qu.: 3.94   1st Qu.:    0.0  
 1      :105   Median :0.7500   Median :15.26   Median :  586.0  
 4      :105   Mean   :0.7296   Mean   :15.06   Mean   :  687.2  
 9      :104   3rd Qu.:0.8000   3rd Qu.:24.26   3rd Qu.: 1083.0  
 10     :100   Max.   :0.8000   Max.   :54.56   Max.

-----
## Factor
범주화를 시킬 때 factor()라는 함수를 사용한다.  

